# Generated by Django 3.0.6 on 2020-05-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0002_hairstyles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyles',
            name='style_img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
