# Generated by Django 3.0.6 on 2020-05-29 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0003_auto_20200528_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('booked_date', models.DateField(default=datetime.datetime(2020, 5, 29, 21, 29, 19, 194532))),
                ('mobile', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
