# Generated by Django 3.0.6 on 2020-05-31 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 12, 2, 20, 667036)),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_gender', models.CharField(max_length=10)),
                ('product_stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloonapp.ProductCategory')),
            ],
        ),
    ]
