# Generated by Django 3.0.6 on 2020-05-31 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0005_auto_20200531_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 23, 49, 58, 938615)),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_cart', models.BooleanField(default=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloonapp.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloonapp.LoginInfo')),
            ],
        ),
    ]
