# Generated by Django 3.0.6 on 2020-06-23 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0008_auto_20200615_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billingdate',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 18, 57, 29, 623303)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 18, 57, 29, 620303)),
        ),
    ]
